#!/bin/bash

# Taken from albfan's answer to
# http://stackoverflow.com/questions/372506/how-can-i-search-git-branches-for-a-file-or-directory

for branch in $(git rev-list --all); do
  git ls-tree -r --name-only $branch | grep "$1" | sed 's/^/'$branch': /'
done
